name: multimodal-integrate
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - cudatoolkit=10.1.243
  - freetype=2.10.2
  - intel-openmp=2020.2
  - joblib=0.16.0
  - jpeg=9b
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.10.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.1.1
  - pillow=7.2.0
  - pip=20.2.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytorch=1.6.0
  - pytz=2020.1
  - readline=8.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - torchvision=0.7.0
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - cycler==0.10.0
    - decorator==4.4.2
    - imageio==2.9.0
    - kiwisolver==1.2.0
    - matplotlib==3.3.2
    - networkx==2.5
    - opencv-python==4.4.0.42
    - pyparsing==2.4.7
    - pywavelets==1.1.1
    - scikit-image==0.17.2
    - tifffile==2020.9.3
